server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/usuarios
    username: demo
    password: demo
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

security:
  jwt:
    private-key-path: classpath:app.key
    public-key-path:  classpath:app.pub
    expiration: 3600000

springdoc:
  swagger-ui:
    path: /swagger-ui.html